### ISSUE TITLE
please report this bug

### ISSUE THREAD

**Issue by lengrongfu** [ofabry/go-callvis#77] opened 2020-11-15 14:45 UTC
Internal panic in pointer analysis:
goroutine 1 [running]:
runtime/debug.Stack(0x24, 0x0, 0x0)
	/home/workspace2/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/home/workspace2/go/src/runtime/debug/stack.go:16 +0x25
golang.org/x/tools/go/pointer.Analyze.func1(0xc0b2aadd70)
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20201114224030-61ea331ec02b/go/pointer/analysis.go:227 +0x10b
panic(0xa9a620, 0xc05c3ba160)
	/home/workspace2/go/src/runtime/panic.go:969 +0x1b9
golang.org/x/tools/go/pointer.(*analysis).taggedValue(0xc0175356c0, 0xc0000409cf, 0x4, 0x64, 0xc0291ff180)
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20201114224030-61ea331ec02b/go/pointer/gen.go:272 +0x105
golang.org/x/tools/go/pointer.(*invokeConstraint).solve(0xc06cbad690, 0xc0175356c0, 0xc055b8d100)
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20201114224030-61ea331ec02b/go/pointer/solve.go:317 +0x24e
golang.org/x/tools/go/pointer.(*analysis).solveConstraints(0xc0175356c0, 0xc06ccea4b0, 0xc055b8d100)
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20201114224030-61ea331ec02b/go/pointer/solve.go:165 +0x178
golang.org/x/tools/go/pointer.(*analysis).solve(0xc0175356c0)
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20201114224030-61ea331ec02b/go/pointer/solve.go:59 +0x1ad
golang.org/x/tools/go/pointer.Analyze(0xc02f739d60, 0x0, 0xc08c80, 0xc05c3ba180)
	/root/go/pkg/mod/golang.org/x/tools@v0.0.0-20201114224030-61ea331ec02b/go/pointer/analysis.go:331 +0x4bc
main.doAnalysis(0x0, 0x0, 0xc000122100, 0xc0000200b0, 0x1, 0x1, 0xb67fb4, 0x16)
	/root/go/src/github.com/ofabry/go-callvis/analysis.go:50 +0x24a
main.main()
	/root/go/src/github.com/ofabry/go-callvis/main.go:107 +0x156
22:43:20.239980 internal error in pointer analysis: not a tagged object: n264655 (please report this bug)

**Comment by lengrongfu** [comment] 2020-11-15 14:47
CentOS Linux release 7.5.1804 (Core)
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/home/workspace2/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/workspace2/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/go/src/k8s.io/kubernetes/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build236581864=/tmp/go-build -gno-record-gcc-switches"

**Comment by ofabry** [comment] 2020-12-29 21:51
Duplicate of https://github.com/ofabry/go-callvis/issues/24

**Closed by ofabry** 2020-12-29 21:51 UTC
